### ISSUE TITLE
Allow server=URL

### ISSUE THREAD

**Issue by rweigel** [hapi-server/server-ui#2]

**Comment by jbfaden** [comment]
I'd like to be able to say http://hapi-server.org/servers/#server=https://jfaden.net/HapiServerDemo/hapi and have strange servers work with this system, or if humans could edit the drop list to add a new entry.

**Comment by rweigel** [comment]
Testing at http://hapi-server.org/servers-dev/#server=http://jfaden.net/HapiServerDemo/hapi

**Comment by jbfaden** [comment]
Bob, this works nicely.  Another nice effect of this is that more servers will allow this code to mature more quickly.  It looks like it has some issue with my time tags, and I can see that my binary responses don't have the ISO8601 Zs while my text responses do.  Progress!

**Comment by rweigel** [comment]
You may want to play with the DAS2 server. The dev page now has a proxy to
allow browsing non-CORS sites.

**Comment by jbfaden** [comment]
I saw that too.  There must be some issue with the Das2 server, and I was going to look at that later today.
