### ISSUE TITLE
the mean of .sss in the timeformat need further clarification

### ISSUE THREAD

**Issue by scottb77** [hapi-server/server-ui#7]
I think the time representation in the document https://github.com/hapi-server/data-specification/blob/master/hapi-dev/HAPI-data-access-spec-dev.md#representation-of-time
 
The meaning of .sss in the output string should be clarified that .sss could be .sssss, or .sssssssss depending upon the time precision of native time stamps of the data to be streamed.
 
yyyy-mm-ddThh:mm:ss.sssZ
or

yyyy-dddThh:mm:ss.sssZ
 
Statement should be included that  the number of digits are in the sub second field could be beyond the milli-second
 
For example to include TT2000  as given the HAPI cdaweb server i.e.
 
'2016-06-10T21:42:24.760738998Z'

**Comment by rweigel** [comment]
This repo is for HTML and Javascript software used for a UI to a HAPI server.

Your issue involves the actual HAPI specification document. Would you post this issue at https://github.com/hapi-server/data-specification?
